version: '3'
services:
  app:
    build: .
    ports:
      - "5001:5001"
      - "5678:5678"
    environment:
      - FLASK_APP=app.py
      - USERS_API_URL=http://users:5002
    volumes:
      - .:/app
    networks:
      - cnvs
    command: flask run --host=0.0.0.0 --port=5001
  users:
    build: .
    ports:
      - "5002"
    environment:
      - FLASK_APP=users_api.py
    volumes:
      - .:/app
    networks:
      - cnvs
    command: flask run --host=0.0.0.0 --port=5002

networks:
  cnvs: